# Generated by Django 4.0.6 on 2023-06-30 12:15

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام قرارداد')),
                ('start_time', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('end_time', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان')),
                ('contract_time', django_jalali.db.models.jDateField(verbose_name='تاریخ انعقاد')),
                ('state', models.CharField(choices=[('فعال', 'فعال'), ('در حال تمدید', 'در حال تمدید'), ('پیش نویس', 'پیش نویس'), ('منقضی کمتر از 30 روز', 'منقضی کمتر از 30 روز'), ('منقضی', 'منقضی')], default='فعال', max_length=25, verbose_name='وضعیت')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
