# Generated by Django 4.0.6 on 2023-07-12 22:10

import contract.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['id'], 'verbose_name': 'قرارداد', 'verbose_name_plural': 'قراردادها'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[contract.models.notes_validator], verbose_name='توضیحات'),
        ),
    ]
