# Generated by Django 4.0.6 on 2023-07-13 13:21

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_options_alter_contract_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_time',
            field=django_jalali.db.models.jDateField(blank=True, default=datetime.datetime.now, verbose_name='تاریخ انعقاد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(default='تتت', max_length=50, verbose_name='نام قرارداد'),
        ),
    ]
