# Generated by Django 4.0.6 on 2023-06-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercialname', models.CharField(max_length=50, unique=True, verbose_name='نام تجاری')),
                ('brand', models.CharField(max_length=25, unique=True, verbose_name='برند')),
                ('city', models.CharField(max_length=15, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن')),
                ('kind', models.CharField(choices=[('عادی', 'عادی'), ('ویژه', 'ویژه')], default='عادی', max_length=4, verbose_name='نوع')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
