# Generated by Django 4.0.6 on 2023-07-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='subnet_mask',
            field=models.PositiveSmallIntegerField(default=32, verbose_name='Subnet Mask'),
        ),
    ]
