# Generated by Django 4.0.6 on 2023-07-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0002_alter_ip_subnet_mask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='cloud',
        ),
    ]
