# Generated by Django 4.0.6 on 2023-06-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('customer', '0001_initial'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Micro', 'Micro'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('XLarge', 'XLarge'), ('XXLarge', 'XXLarge')], default='Medium', max_length=7)),
                ('ip', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('agents', models.ManyToManyField(blank=True, to='agent.agent')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
