# Generated by Django 4.0.6 on 2023-07-03 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudExtraIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('subnet_mask', models.PositiveSmallIntegerField(verbose_name='Subnet Mask')),
                ('cloud', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cloud.cloud')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
