# Generated by Django 4.0.6 on 2023-07-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_cloudextraip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloudExtraIP',
        ),
    ]
