# Generated by Django 4.0.6 on 2023-07-20 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('contract', '0003_alter_contract_contract_time_alter_contract_name'),
        ('customer', '0001_initial'),
        ('cloud', '0004_remove_cloud_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='agents',
            field=models.ManyToManyField(blank=True, to='agent.agent', verbose_name='نماینده'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract', verbose_name='قرارداد'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='مشترک'),
        ),
    ]
