# Generated by Django 4.0.6 on 2023-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0003_remove_ip_cloud'),
        ('cloud', '0005_alter_cloud_agents_alter_cloud_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='ips',
            field=models.ManyToManyField(blank=True, to='ip.ip', verbose_name='آی پی ها'),
        ),
    ]
